### ISSUE TITLE
Possible bug: how to obtain "xt.pt"?

### ISSUE THREAD

**Issue by shahviraj** [MagicFusion/MagicFusion.github.io#4]
While trying to run the code, I get an error on [line 98 in ddim.py](https://github.com/MagicFusion/MagicFusion.github.io/blob/4d9e42011b962e3466ad6af478d33f193ca97389/ldm/models/diffusion/ddim.py#L98) that the file xt.pt is not found. Any help in resolving the issue is greatly appreciated. 

P.S. : From my reading of the code, I believe this statement should be replaced by `self.noise = torch.randn([1,4,64,64], device=torch.device('cuda'))`

**Comment by MagicFusion** [comment]
> While trying to run the code, I get an error on [line 98 in ddim.py](https://github.com/MagicFusion/MagicFusion.github.io/blob/4d9e42011b962e3466ad6af478d33f193ca97389/ldm/models/diffusion/ddim.py#L98) that the file xt.pt is not found. Any help in resolving the issue is greatly appreciated.
> 
> P.S. : From my reading of the code, I believe this statement should be replaced by `self.noise = torch.randn([1,4,64,64], device=torch.device('cuda'))`

I'm sorry about the issue in the code. you are right, xt.pt here is randomly initialized noise. you can easily generate new noise with the torch.randn function.
